---
# This is the name of the world in which meetup games will start
# Note: the world must be loaded to work properly
meetup-world: world

# Allow spectators in your game and put players on spectator gamemode on their death
spectators: true

# Type the game length in minutes (max. 60)
length: 20

# Every block placed while the game is running will be removed at the end of the Meetup
reset: true
...